[tool.ruff]
line-length = 100
target-version = "py311"
lint.select = ["E","F","I","UP","B","C4","SIM","ARG"]
lint.ignore = ["E203", "E266", "E501", "B008"]

[tool.mypy]
python_version = "3.11"
warn_unused_configs = true
disallow_untyped_defs = true
no_implicit_optional = true
check_untyped_defs = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_return_any = false
exclude = ["tests/"]
